baseURL = "/"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "almeida-cv"
title = "Jack Holgado"

[params]
colorDark = "#666"
colorLight = "#fff"
colorPageBackground = "#ddd"
colorPrimary = "#8fc7aa"
colorPrimaryText = "#fff"
colorRightColumnBackground = "#f5f5f5"
colorSecondary = "#aaa"
pages = 2
